# Generated by Django 5.2 on 2025-04-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0002_alter_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
