# Generated by Django 5.2 on 2025-04-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0003_chatsession_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
