# Generated by Django 5.2 on 2025-04-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0004_chatsession_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
