# Generated by Django 5.2 on 2025-05-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_api', '0005_chatmessage_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_charts/'),
        ),
    ]
