# Generated by Django 5.2 on 2025-04-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptbox_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptboxitem',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
